/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AttachmentsIdImport } from './routes/attachments/$id'

// Create Virtual Routes

const UploadLazyImport = createFileRoute('/upload')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UploadLazyRoute = UploadLazyImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/upload.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AttachmentsIdRoute = AttachmentsIdImport.update({
  id: '/attachments/$id',
  path: '/attachments/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/attachments/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadLazyImport
      parentRoute: typeof rootRoute
    }
    '/attachments/$id': {
      id: '/attachments/$id'
      path: '/attachments/$id'
      fullPath: '/attachments/$id'
      preLoaderRoute: typeof AttachmentsIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/upload': typeof UploadLazyRoute
  '/attachments/$id': typeof AttachmentsIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/upload': typeof UploadLazyRoute
  '/attachments/$id': typeof AttachmentsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/upload': typeof UploadLazyRoute
  '/attachments/$id': typeof AttachmentsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upload' | '/attachments/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/upload' | '/attachments/$id'
  id: '__root__' | '/' | '/upload' | '/attachments/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  UploadLazyRoute: typeof UploadLazyRoute
  AttachmentsIdRoute: typeof AttachmentsIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  UploadLazyRoute: UploadLazyRoute,
  AttachmentsIdRoute: AttachmentsIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/upload",
        "/attachments/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/upload": {
      "filePath": "upload.lazy.tsx"
    },
    "/attachments/$id": {
      "filePath": "attachments/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
